# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e54d2637da0269d8c0ff7c83b6cf9813f3ee0786145ef6c6b47bce245391798f05d750ae00e0548885038cfd94502786b05281e942bd504021a923047d9e2c

test:
  secret_key_base: 82d96aefb1709b5025e8ed8bb81745d039201a7acb900377dd26f1c2270cb1a4ac6eb6128ca33d80bad946bea9ca854545c8b7718124747531ee5a9537377a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
